FROM ubuntu:18.04

RUN apt-get update
RUN apt-get install -y make

RUN apt-get install -y cmake

RUN apt-get install -y g++

RUN apt-get install -y libmysqlcppconn-dev

RUN apt-get install -y libboost-all-dev

RUN apt-get install -y libmysqlclient-dev

WORKDIR /crawler